Mo check out test
SamRouse123/FinalAutomationProject pull request #2
Opened 2023-04-17 08:35 UTC by Moelnur

-Created basket.feature page
- Created BasketStepDefs for testing quantity in the basket
- Created BasketPage for methods on basket page
- Created TShirtPage for methods on the selected item

2023-04-17 09:43 UTC, tuhelahmed98 approved these changes
Fantastic work:)

2023-04-17 10:07 UTC, matthewmccormick requested changes

2023-04-17 10:07 UTC, matthewmccormick commented on src/test/java/stepDefinitions/BasketStepDefs.java
> +public void clickOnItem(){
@Moelnur Can you reformat this file please before merging

2023-04-17 10:40 UTC, selena92 approved these changes
Nice work :)

2023-04-17 15:03 UTC, SamRouse123 commented
Great work!

2023-04-18 13:36 UTC, matthewmccormick approved these changes

2023-04-18 13:41 UTC, merged